# Generated by Django 4.2.3 on 2023-07-28 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components_of_device', '0002_monitordisplay_monitorergonomics_monitorfeatures_and_more'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product')),
                ('display', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor_display', to='components_of_device.monitordisplay')),
                ('ergonomics', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ergonomics', to='components_of_device.monitorergonomics')),
                ('features', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='components_of_device.monitorfeatures')),
                ('key_specification', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key_specification', to='components_of_device.monitorkeyspecification')),
                ('physical', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='physical', to='components_of_device.monitorphysical')),
                ('ports', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitors_ports', to='components_of_device.monitorports')),
            ],
            bases=('product.product',),
        ),
    ]
