# Generated by Django 4.2.3 on 2023-07-29 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components_of_device', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product')),
                ('operating_system', models.CharField(blank=True, max_length=50, null=True)),
                ('ssd_capacity', models.IntegerField(blank=True, null=True)),
                ('chassis', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='computer_chassis', to='components_of_device.computerchassis')),
                ('graphics', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='computer_graphics', to='components_of_device.computergraphics')),
                ('memory', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='computer_memory', to='components_of_device.computermemory')),
                ('ports_and_connectivity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='computer_ports', to='components_of_device.computerportsandconnectivity')),
                ('processor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='computer_processor', to='components_of_device.computerprocessor')),
            ],
            bases=('product.product',),
        ),
    ]
