# Generated by Django 4.2.3 on 2023-07-29 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components_of_device', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product')),
                ('ssd_capacity', models.IntegerField(blank=True, default=0, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=50, null=True)),
                ('battery', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battery', to='components_of_device.laptopbattery')),
                ('chassis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chassis', to='components_of_device.laptopchassis')),
                ('display', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='display', to='components_of_device.laptopdisplay')),
                ('graphics', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graphics', to='components_of_device.laptopgraphics')),
                ('keyboard', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keyboard', to='components_of_device.laptopkeyboard')),
                ('memory', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memory', to='components_of_device.laptopmemory')),
                ('ports_and_connectivity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='components_of_device.laptopportsandconnectivity')),
                ('processor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processor', to='components_of_device.laptopprocessor')),
            ],
            bases=('product.product',),
        ),
    ]
