# Generated by Django 4.2.3 on 2023-07-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='laptop_type',
            field=models.CharField(blank=True, choices=[('Gaming', 'Gaming'), ('MacBooks', 'MacBooks'), ('Chromebooks', 'Chromebooks')], default='Chromebooks', max_length=20, null=True),
        ),
    ]
