# Generated by Django 4.2.3 on 2023-07-26 15:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components_of_device', '0001_initial'),
        ('product', '0002_product_condition_product_warranty'),
        ('laptops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='id',
        ),
        migrations.AddField(
            model_name='laptop',
            name='battery',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battery', to='components_of_device.battery'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='chassis',
            field=models.OneToOneField(default=datetime.datetime(2023, 7, 26, 15, 11, 43, 903170, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, related_name='chassis', to='components_of_device.chassis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop',
            name='display',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='display', to='components_of_device.display'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='graphics',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graphics', to='components_of_device.graphics'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='keyboard',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keyboard', to='components_of_device.keyboard'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='memory',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memory', to='components_of_device.memory'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='operating_system',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='ports_and_connectivity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='components_of_device.portsandconnectivity'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='processor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processor', to='components_of_device.processor'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='product_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop',
            name='ssd_capacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
