# Generated by Django 4.2.3 on 2023-07-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerChassis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('form_factor', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComputerGraphics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graphics_type', models.CharField(blank=True, max_length=50, null=True)),
                ('graphics_manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('graphics_card', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComputerMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installed_size', models.IntegerField(blank=True, null=True)),
                ('speed', models.IntegerField(blank=True, null=True)),
                ('memory_type', models.CharField(blank=True, max_length=20, null=True)),
                ('form_factor', models.CharField(blank=True, max_length=20, null=True)),
                ('total_slots', models.IntegerField(blank=True, null=True)),
                ('maximum_capacity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComputerPortsAndConnectivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usb_2_0', models.IntegerField(blank=True, default=0, null=True)),
                ('usb_3_0', models.IntegerField(blank=True, default=0, null=True)),
                ('hdmi', models.IntegerField(blank=True, default=0, null=True)),
                ('display_port', models.IntegerField(blank=True, default=0, null=True)),
                ('dvi', models.IntegerField(blank=True, default=0, null=True)),
                ('vga', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComputerProcessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(blank=True, max_length=30, null=True)),
                ('series', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('generation', models.CharField(blank=True, max_length=20, null=True)),
                ('cores', models.IntegerField(blank=True, null=True)),
                ('cache_size', models.IntegerField(blank=True, null=True)),
                ('clock_speed', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaptopBattery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_time', models.IntegerField(blank=True, null=True)),
                ('technology', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaptopChassis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('optical_drive', models.CharField(blank=True, max_length=50, null=True)),
                ('webcam', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaptopDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_size', models.CharField(blank=True, max_length=30, null=True)),
                ('resolution', models.CharField(blank=True, max_length=30, null=True)),
                ('refresh_rate', models.IntegerField(blank=True, null=True)),
                ('screen_type', models.CharField(blank=True, max_length=30, null=True)),
                ('brightness', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaptopGraphics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graphics_type', models.CharField(blank=True, max_length=50, null=True)),
                ('graphics_manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('graphics_card', models.CharField(blank=True, max_length=100, null=True)),
                ('integrated_graphics', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaptopKeyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backlit_keyboard', models.BooleanField(blank=True, default=False, null=True)),
                ('numeric_keyboard', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaptopMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installed_size', models.IntegerField(blank=True, null=True)),
                ('speed', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaptopPortsAndConnectivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usb_3_0', models.IntegerField(blank=True, default=0, null=True)),
                ('usb_c', models.IntegerField(blank=True, default=0, null=True)),
                ('hdmi', models.IntegerField(blank=True, default=0, null=True)),
                ('wifi', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaptopProcessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(blank=True, max_length=30, null=True)),
                ('series', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('cores', models.IntegerField(blank=True, null=True)),
                ('clock_speed', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('boost_frequency', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonitorDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_size', models.CharField(blank=True, max_length=30, null=True)),
                ('resolution', models.CharField(blank=True, max_length=30, null=True)),
                ('refresh_rate', models.IntegerField(blank=True, null=True)),
                ('screen_type', models.CharField(blank=True, max_length=30, null=True)),
                ('brightness', models.CharField(blank=True, max_length=30, null=True)),
                ('aspect_ratio', models.CharField(blank=True, max_length=30, null=True)),
                ('panel_type', models.CharField(blank=True, max_length=60, null=True)),
                ('display_type', models.CharField(blank=True, max_length=70, null=True)),
                ('vertical_viewing_angle', models.IntegerField(blank=True, null=True)),
                ('horizontal_viewing_angle', models.IntegerField(blank=True, null=True)),
                ('TFT_technology', models.CharField(blank=True, max_length=50, null=True)),
                ('image_contrast_ratio', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonitorErgonomics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_adjustment', models.BooleanField(blank=True, default=False, null=True)),
                ('tilt', models.BooleanField(blank=True, default=False, null=True)),
                ('pivot', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonitorFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_sync', models.BooleanField(blank=True, default=False, null=True)),
                ('hdr', models.BooleanField(blank=True, default=False, null=True)),
                ('speakers', models.BooleanField(blank=True, default=False, null=True)),
                ('console_compatibility', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonitorKeySpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_size', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('maximum_resolution', models.CharField(blank=True, max_length=20, null=True)),
                ('hdmi_type', models.CharField(blank=True, max_length=20, null=True)),
                ('aspect_ratio', models.CharField(blank=True, max_length=20, null=True)),
                ('panel_type', models.CharField(blank=True, max_length=40, null=True)),
                ('refresh_rate', models.IntegerField(blank=True, null=True)),
                ('response_time', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonitorPhysical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('wall_mounting', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonitorPorts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usb_3_0', models.IntegerField(blank=True, default=0, null=True)),
                ('usb_c', models.IntegerField(blank=True, default=0, null=True)),
                ('hdmi', models.IntegerField(blank=True, default=0, null=True)),
                ('display_port', models.IntegerField(blank=True, default=0, null=True)),
                ('mini_display_port', models.IntegerField(blank=True, default=0, null=True)),
                ('HDMI_type', models.CharField(blank=True, max_length=30, null=True)),
                ('VGA', models.IntegerField(blank=True, default=0, null=True)),
                ('DVI', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_camera', models.IntegerField(blank=True, null=True)),
                ('rear_camera', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneConnectivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_speeds', models.CharField(blank=True, max_length=5, null=True)),
                ('bluetooth', models.BooleanField(blank=True, default=False, null=True)),
                ('wifi', models.BooleanField(blank=True, default=False, null=True)),
                ('nfc', models.BooleanField(blank=True, default=False, null=True)),
                ('gps', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneDimensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_size', models.IntegerField(blank=True, null=True)),
                ('screen_resolution', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=80, null=True)),
                ('model', models.CharField(blank=True, max_length=150, null=True)),
                ('colour', models.CharField(blank=True, max_length=40, null=True)),
                ('network', models.CharField(blank=True, max_length=80, null=True)),
                ('phone_agreement', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhonePower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charging_port', models.CharField(blank=True, max_length=50, null=True)),
                ('battery_capacity', models.IntegerField(blank=True, null=True)),
                ('talk_time', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_storage', models.IntegerField(blank=True, null=True)),
                ('memory_card_support', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneTechnicalSpecifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_system', models.CharField(blank=True, max_length=50, null=True)),
                ('processor_type', models.CharField(blank=True, max_length=50, null=True)),
                ('processor_speed', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('ram', models.IntegerField(blank=True, null=True)),
                ('sim_type', models.CharField(blank=True, max_length=50, null=True)),
                ('dual_sim', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TabletCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_camera', models.IntegerField(blank=True, null=True)),
                ('back_camera', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TabletsBattery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runtime', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TabletsDimensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_size', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('tablet_size', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TabletsKeySpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.IntegerField(blank=True, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=80, null=True)),
                ('processor_clock_speed', models.IntegerField(blank=True, null=True)),
                ('RAM', models.IntegerField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TabletsOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=80, null=True)),
                ('model', models.CharField(blank=True, max_length=150, null=True)),
                ('colour', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TabletsPortsAndConnectivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connectivity', models.CharField(blank=True, max_length=80, null=True)),
                ('bluetooth', models.CharField(blank=True, max_length=80, null=True)),
                ('card_reader', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
    ]
