# Generated by Django 4.2.3 on 2023-07-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_time', models.IntegerField(blank=True, null=True)),
                ('technology', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chassis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('optical_drive', models.CharField(blank=True, max_length=50, null=True)),
                ('webcam', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_size', models.CharField(blank=True, max_length=30, null=True)),
                ('resolution', models.CharField(blank=True, max_length=30, null=True)),
                ('refresh_rate', models.IntegerField(blank=True, null=True)),
                ('screen_type', models.CharField(blank=True, max_length=30, null=True)),
                ('brightness', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Graphics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graphics_type', models.CharField(blank=True, max_length=50, null=True)),
                ('graphics_manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('graphics_card', models.CharField(blank=True, max_length=100, null=True)),
                ('integrated_graphics', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backlit_keyboard', models.BooleanField(blank=True, default=False, null=True)),
                ('numeric_keyboard', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installed_size', models.IntegerField(blank=True, null=True)),
                ('speed', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortsAndConnectivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usb_3_0', models.IntegerField(blank=True, default=0, null=True)),
                ('usb_c', models.IntegerField(blank=True, default=0, null=True)),
                ('hdmi', models.IntegerField(blank=True, default=0, null=True)),
                ('wifi', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(blank=True, max_length=30, null=True)),
                ('series', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('cores', models.IntegerField(blank=True, null=True)),
                ('clock_speed', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('boost_frequency', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
            ],
        ),
    ]
