# Generated by Django 4.2.3 on 2023-07-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components_of_device', '0002_monitordisplay_monitorergonomics_monitorfeatures_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabletCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_camera', models.IntegerField(blank=True, null=True)),
                ('back_camera', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TabletsBattery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runtime', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TabletsDimensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_size', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('tablet_size', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TabletsKeySpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.IntegerField(blank=True, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=80, null=True)),
                ('processor_clock_speed', models.IntegerField(blank=True, null=True)),
                ('RAM', models.IntegerField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TabletsOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=80, null=True)),
                ('model', models.CharField(blank=True, max_length=150, null=True)),
                ('colour', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TabletsPortsAndConnectivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connectivity', models.CharField(blank=True, max_length=80, null=True)),
                ('bluetooth', models.CharField(blank=True, max_length=80, null=True)),
                ('card_reader', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
    ]
