# Generated by Django 4.2.3 on 2023-07-29 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components_of_device', '0003_tabletcamera_tabletsbattery_tabletsdimensions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_camera', models.IntegerField(blank=True, null=True)),
                ('rear_camera', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneConnectivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_speeds', models.CharField(blank=True, max_length=5, null=True)),
                ('bluetooth', models.BooleanField(blank=True, default=False, null=True)),
                ('wifi', models.BooleanField(blank=True, default=False, null=True)),
                ('nfc', models.BooleanField(blank=True, default=False, null=True)),
                ('gps', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneDimensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_size', models.IntegerField(blank=True, null=True)),
                ('screen_resolution', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneOverview',
            fields=[
                ('tabletsoverview_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components_of_device.tabletsoverview')),
                ('network', models.CharField(blank=True, max_length=80, null=True)),
                ('phone_agreement', models.CharField(blank=True, max_length=80, null=True)),
            ],
            bases=('components_of_device.tabletsoverview',),
        ),
        migrations.CreateModel(
            name='PhonePower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charging_port', models.CharField(blank=True, max_length=50, null=True)),
                ('battery_capacity', models.IntegerField(blank=True, null=True)),
                ('talk_time', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_storage', models.IntegerField(blank=True, null=True)),
                ('memory_card_support', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneTechnicalSpecifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_system', models.CharField(blank=True, max_length=50, null=True)),
                ('processor_type', models.CharField(blank=True, max_length=50, null=True)),
                ('processor_speed', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('ram', models.IntegerField(blank=True, null=True)),
                ('sim_type', models.CharField(blank=True, max_length=50, null=True)),
                ('dual_sim', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
