# Generated by Django 4.2.3 on 2023-07-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablets',
            name='phone_type',
            field=models.CharField(blank=True, choices=[('iPads', 'iPads'), ('Surface', 'Surface'), ('Android', 'Android')], default='Android', max_length=20, null=True),
        ),
    ]
