# Generated by Django 4.2.3 on 2023-07-30 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablets', '0002_tablets_phone_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablets',
            old_name='phone_type',
            new_name='tablets_type',
        ),
    ]
